env:
  - KO_DOCKER_REPO=ghcr.io/{{ .Env.GITHUB_REPOSITORY }}
builds:
  - main: ./cmd/{{ .ProjectName }}/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
universal_binaries:
  - replace: false
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - typo
release:
  prerelease: auto
kos:
  - base_image: cgr.dev/chainguard/static
    bare: true
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
    - latest
    - '{{.Tag}}'
    creation_time: '{{.CommitTimestamp}}'
